const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const { AgenticLoopManager } = require("../src/runtime/agentic_loop");
const { analyzeRunSemantics } = require("../src/runtime/semantics");
const { createScenarioHtml, startStaticServer, writeSite } = require("./helpers/site_factory");

function buildMatrix() {
  return [
    { name: "dynamic-pass", behavior: "changes_state", expectedStatus: "pass" },
    { name: "dynamic-fail-no-change", behavior: "no_change", expectedStatus: "fail" },
    { name: "dynamic-pass-missing-button", behavior: "missing_button", expectedStatus: "pass" }
  ];
}

async function executeScenario(manager, root, scenario) {
  const built = createScenarioHtml(scenario);
  const siteDir = writeSite(root, scenario.name, built.html);
  const { server, url } = await startStaticServer(siteDir);
  try {
    const result = await manager.orchestrateTask({
      projectName: scenario.name,
      task: `Validate ${scenario.name} behavior`,
      url,
      notes: "Generated by test harness",
      additions: "",
      skipCodex: true
    });
    return { result, url, expected: built.expected };
  } finally {
    server.close();
  }
}

async function run() {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "jungle-orch-sem-"));
  fs.writeFileSync(path.join(tmp, ".env"), "GEMINI_API_KEY=\n", "utf8");
  const manager = new AgenticLoopManager(tmp);
  const matrix = buildMatrix();

  const observed = [];
  for (const scenario of matrix) {
    const { result } = await executeScenario(manager, tmp, scenario);
    assert.ok(result.run, `${scenario.name}: missing run`);
    assert.ok(result.run.runId, `${scenario.name}: missing run id`);
    assert.ok(result.run.videoPath, `${scenario.name}: missing video path`);
    assert.ok(result.run.semantics, `${scenario.name}: missing stored semantics`);

    const semantic = analyzeRunSemantics(result.run, tmp);
    const statusMatches = result.run.status === scenario.expectedStatus;
    assert.ok(
      statusMatches,
      `${scenario.name}: expected status ${scenario.expectedStatus}, got ${result.run.status} (${result.run.summary})`
    );
    assert.ok(
      semantic.video.valid,
      `${scenario.name}: expected valid webm video. details=${JSON.stringify(semantic.video)}`
    );

    if (scenario.expectedStatus === "pass") {
      assert.ok(semantic.overallPass, `${scenario.name}: pass run should have overallPass semantics`);
      assert.equal(semantic.wrong.length, 0, `${scenario.name}: pass run should not have wrong checks`);
    } else {
      assert.ok(!semantic.overallPass, `${scenario.name}: fail run should not have overallPass semantics`);
      assert.ok(semantic.wrong.length > 0, `${scenario.name}: fail run should have wrong-check reasoning`);
      assert.ok(
        result.run.steps.some((s) => s.status === "fail"),
        `${scenario.name}: fail run should include at least one failed step`
      );
    }

    observed.push({
      name: scenario.name,
      status: result.run.status,
      semanticVerdict: semantic.verdict,
      wrongCount: semantic.wrong.length
    });
  }

  const hasPass = observed.some((r) => r.status === "pass");
  const hasFail = observed.some((r) => r.status === "fail");
  assert.ok(hasPass && hasFail, "matrix should include both passing and failing outcomes");

  console.log("agentic_orchestration_semantics.test.js passed", observed);
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
